#!/bin/bash

# Source the .env file if it exists
if [ -f .env ]; then
  echo "Loading environment variables from .env file..."
  source .env
fi

# Export environment variables to be available for other scripts
export MY_SECRET_PASSWORD

# Use the secret in your application
echo "Environment variable MY_SECRET_PASSWORD is set"



echo "Starting JupyterLab with custom attributes..."
jupyter lab --AiExtension.default_language_model=anthropic-chat:claude-2.1
