name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r binder/requirements.txt

    - name: Set up API key
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env


    - name: Push .env to repository
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "ssp24@mailbox.org"
        git config --global user.name "SN"
        git add .env
        git commit -m "Add .env file with secret token"
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
