name: Pass Token to Binder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pass token to Binder
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Push .env to repository
      run: |
        git config --global user.email "ssp24@mailbox.org"
        git config --global user.name "SN"
        git add .env
        git commit -m "Add .env file with secret token"
        git push
